### ISSUE TITLE
Change HTTP port from 80 to 6001

### ISSUE THREAD

**Issue by dustsigns** [sproof/docs#15]
As pointed out in [a comment in the last PR](https://github.com/sproof/docs/pull/13#issuecomment-552181163), setting up the docker client requires port 80 to be free, although the documentation as well as the final server uses port 6001 by default. This behavior should be changed so that it matches the documentation, i.e., port 80 should not be used unless the user explicitly specifies it.

**Comment by cle1000** [comment]
> 6001
Done: https://github.com/sproof/sproof-api-client/commit/6be5206a3a00bef75feeaa380c4a18c067abde0a
